name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/component-lint.yml@v0.20.3
    with:
      json: true
